# we need trusty because test-cmd depends on jq  version >= 1.5
dist : trusty
sudo: required


language: go

go:
  - 1.6

install:
  - true

script:
  - make validate
  - make test-unit
  
  # make test-cmd requires kompose binary
  - make binary
  
  # $GOPATH/bin is in $PATH
  - mkdir -p $GOPATH/bin
  - cp kompose $GOPATH/bin/

  - make test-cmd
