# we need trusty because test-cmd depends on jq  version >= 1.5
dist : trusty
sudo: required


language: go

go:
  - 1.6

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/modocache/gover

install:
  - true

script:
  - make validate
  - make test-unit-cover
  # gover collects all .coverprofile files and saves it to one file gover.coverprofile
  - gover
  - goveralls -coverprofile=gover.coverprofile -service=travis-ci
  
  # make test-cmd requires kompose binary
  - make bin
  
  # $GOPATH/bin is in $PATH
  - mkdir -p $GOPATH/bin
  - cp kompose $GOPATH/bin/

  - make test-cmd
